# Default values for auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: pyltsin/auth:1.0

service:
  type: NodePort
  port: 8080

ingress:
  enabled: false

autoscaling:
  enabled: false
