apiVersion: v2
name: hello-charts
description: A Helm chart for Kubernetes

type: application

version: 0.6.0
appVersion: 2.0

dependencies:
  - name: postgresql
    version: 8.9.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - myapp-database
